# Generated by Django 5.2.14 on 2026-05-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFeedbackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('lecture_objective', models.TextField(blank=True)),
                ('student_code', models.TextField()),
                ('execution_status', models.CharField(blank=True, max_length=50)),
                ('execution_stdout', models.TextField(blank=True)),
                ('execution_stderr', models.TextField(blank=True)),
                ('error_category', models.CharField(blank=True, max_length=100)),
                ('feedback_level', models.CharField(blank=True, max_length=50)),
                ('concept_reference', models.CharField(blank=True, max_length=200)),
                ('feedback_text', models.TextField(blank=True)),
                ('does_reveal_solution', models.BooleanField(default=False)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('ai_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
