# Generated by Django 5.2.14 on 2026-05-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefeedbackrecord',
            name='llm_used',
            field=models.CharField(default='deepseek', max_length=50),
        ),
    ]
