# Generated by Django 5.2.14 on 2026-09-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0006_schema_status_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dataset_name', models.CharField(default='Refactory', max_length=100)),
                ('dataset_path', models.CharField(blank=True, default='', max_length=500)),
                ('dataset_size', models.PositiveIntegerField(default=0)),
                ('providers', models.JSONField(blank=True, default=list)),
                ('prompt_versions', models.JSONField(blank=True, default=list)),
                ('run_mode', models.CharField(choices=[('dry_run', 'Dry run'), ('llm', 'LLM API run')], default='dry_run', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('summary', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100)),
                ('source_dataset', models.CharField(default='Refactory', max_length=100)),
                ('source_record_path', models.CharField(blank=True, default='', max_length=500)),
                ('source_test_input_path', models.CharField(blank=True, default='', max_length=500)),
                ('source_test_output_path', models.CharField(blank=True, default='', max_length=500)),
                ('provider', models.CharField(max_length=50)),
                ('prompt_version', models.CharField(max_length=50)),
                ('ground_truth_category', models.CharField(max_length=100)),
                ('predicted_category', models.CharField(blank=True, default='', max_length=100)),
                ('category_match', models.BooleanField(blank=True, null=True)),
                ('feedback_level', models.CharField(blank=True, default='', max_length=50)),
                ('concept_reference', models.CharField(blank=True, default='', max_length=200)),
                ('feedback_text', models.TextField(blank=True, default='')),
                ('suggested_next_step', models.TextField(blank=True, default='')),
                ('confidence', models.CharField(blank=True, default='', max_length=50)),
                ('json_compliance', models.BooleanField(blank=True, null=True)),
                ('schema_validation_status', models.CharField(blank=True, default='', max_length=50)),
                ('schema_validation_notes', models.TextField(blank=True, default='')),
                ('solution_leakage_flag', models.BooleanField(blank=True, null=True)),
                ('uses_runtime_evidence', models.BooleanField(blank=True, null=True)),
                ('execution_status', models.CharField(blank=True, default='', max_length=50)),
                ('output_comparison_status', models.CharField(blank=True, default='', max_length=50)),
                ('actual_output', models.TextField(blank=True, default='')),
                ('actual_stderr', models.TextField(blank=True, default='')),
                ('prompt_text', models.TextField(blank=True, default='')),
                ('raw_ai_response', models.TextField(blank=True, default='')),
                ('ai_error', models.TextField(blank=True, default='')),
                ('llm_model_name', models.CharField(blank=True, default='', max_length=100)),
                ('llm_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('llm_token_usage', models.JSONField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='feedback_app.evaluationrun')),
            ],
            options={
                'ordering': ['evaluation_run', 'sample_id', 'provider', 'prompt_version'],
                'unique_together': {('evaluation_run', 'sample_id', 'provider', 'prompt_version')},
            },
        ),
    ]
