# Generated by Django 5.2.14 on 2026-09-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0007_evaluationrun_evaluationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresult',
            name='actionability_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='helpfulness_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='human_review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='human_solution_leakage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='lecture_alignment_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
