# Generated by Django 5.2.14 on 2026-09-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0008_evaluationresult_actionability_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefeedbackrecord',
            name='feedback_schema_version',
            field=models.CharField(blank=True, default='feedback_schema_v2', max_length=50),
        ),
    ]
