# Generated by Django 5.2.14 on 2026-09-17 11:29

from django.db import migrations, models


def preserve_legacy_categories(apps, schema_editor):
    CodeFeedbackRecord = apps.get_model('feedback_app', 'CodeFeedbackRecord')
    for record in CodeFeedbackRecord.objects.exclude(error_category='').iterator():
        record.legacy_error_category = record.error_category
        record.save(update_fields=['legacy_error_category'])


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0009_alter_codefeedbackrecord_feedback_schema_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefeedbackrecord',
            name='classification_outcome',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='codefeedbackrecord',
            name='legacy_error_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='codefeedbackrecord',
            name='peci_error_code',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='codefeedbackrecord',
            name='peci_error_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(preserve_legacy_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='codefeedbackrecord',
            name='feedback_schema_version',
            field=models.CharField(blank=True, default='feedback_schema_v3_peci', max_length=50),
        ),
    ]
