# Generated by Django 5.2.14 on 2026-09-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0010_codefeedbackrecord_classification_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefeedbackrecord',
            name='misconception',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='codefeedbackrecord',
            name='trajectory_attempt_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codefeedbackrecord',
            name='trajectory_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
