# Generated by Django 5.2.14 on 2026-09-17 16:15

from django.db import migrations, models


def backfill_solved(apps, schema_editor):
    record = apps.get_model("feedback_app", "CodeFeedbackRecord")
    record.objects.filter(classification_outcome="no_error").update(solved=True)
    record.objects.filter(error_category__iexact="No Error").update(solved=True)


def clear_solved(apps, schema_editor):
    record = apps.get_model("feedback_app", "CodeFeedbackRecord")
    record.objects.update(solved=False)


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0011_codefeedbackrecord_misconception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefeedbackrecord',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_solved, clear_solved),
    ]
